name: Patch GO_EXPERIENCE

on:
  workflow_dispatch:

jobs:
  patch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'

    - name: Download baksmali/smali
      run: |
        curl -LO https://github.com/JesusFreke/smali/releases/download/v2.5.2/baksmali-2.5.2.jar
        curl -LO https://github.com/JesusFreke/smali/releases/download/v2.5.2/smali-2.5.2.jar

    - name: Unzip services.jar
      run: |
        mkdir temp
        unzip input/services.jar -d temp

    - name: Decompile classes.dex
      run: |
        java -jar baksmali-2.5.2.jar d temp/classes.dex -o smali_out

    - name: PATCH smali (disable GO_EXPERIENCE)
      run: |
        find smali_out -type f -name "*.smali" -exec sed -i 's/GO_EXPERIENCE/GO_DISABLED/g' {} +

    - name: Rebuild classes.dex
      run: |
        java -jar smali-2.5.2.jar a smali_out -o new_classes.dex

    - name: Repack services.jar
      run: |
        cp new_classes.dex temp/classes.dex
        cd temp && zip -r ../services_patched.jar *

    - name: Upload patched file
  uses: actions/upload-artifact@v3
  with:
    name: patched-services
    path: output/services.jar

    - name: Upload hasil services_patched.jar
      uses: actions/upload-artifact@v3
      with:
        name: patched-services
        path: services_patched.jar
