name: Patch GO_EXPERIENCE in services.jar

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Java and smali/baksmali
        run: |
          sudo apt-get update
          sudo apt-get install -y default-jdk wget unzip
          wget https://github.com/JesusFreke/smali/releases/download/v2.5.2/baksmali-2.5.2.jar -O baksmali.jar
          wget https://github.com/JesusFreke/smali/releases/download/v2.5.2/smali-2.5.2.jar -O smali.jar

      - name: Buat folder input/output/temp
        run: mkdir -p input output temp smali

      - name: Upload placeholder
        run: echo "Silakan upload file services.jar ke folder input"

      - name: Upload input file
        uses: actions/upload-artifact@v3
        with:
          name: upload-services
          path: input/

      - name: Download input services.jar
        uses: actions/download-artifact@v3
        with:
          name: upload-services
          path: input/

      - name: Extract classes.dex dari services.jar
        run: |
          unzip -o input/services.jar classes.dex -d temp/

      - name: Baksmali:convert classes.dex to smali
        run: |
          java -jar baksmali.jar d temp/classes.dex -o smali/

      - name: Patch smali - Remove GO_EXPERIENCE
        run: |
          find smali -type f -name "*.smali" -exec sed -i 's/GO_EXPERIENCE/NORMAL/g' {} \;

      - name: Smali:rebuild classes.dex dari smali
        run: |
          java -jar smali.jar a smali/ -o temp/classes.dex

      - name: Repack services.jar
        run: |
          cd temp
          zip -r ../output/services.jar classes.dex
          cd ..

      - name: Upload hasil services.jar
        uses: actions/upload-artifact@v3
        with:
          name: patched-services
          path: output/services.jar
